version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: rbac_user
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: rbacdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  identity-service:
    build:
      context: ./src/ApiIdentityService
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=rbacdb;Username=rbac_user;Password=secretpassword
      Jwt__SecretKey: Tu-Super-Secreto-Clave-JWT-Debe-Tener-Minimo-32-Caracteres-Para-HS256-Algoritmo!
    depends_on:
      - postgres
    ports:
      - "5001:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro    # ⚡ Sincroniza hora con host
      - /etc/timezone:/etc/timezone:ro      # ⚡ Zona horaria correcta

  resource-service:
    build:
      context: ./src/ApiResourceService
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ASPNETCORE_ENVIRONMENT: Development
      Jwt__SecretKey: Tu-Super-Secreto-Clave-JWT-Debe-Tener-Minimo-32-Caracteres-Para-HS256-Algoritmo!
    depends_on:
      - identity-service
    ports:
      - "5002:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  postgres_data:
